/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_28Mei2024;

/**
 *
 * @author ACER
 */
public class FromStudentREcord extends javax.swing.JFrame {

    /**
     * Creates new form FromStudentREcord
     */
    public FromStudentREcord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMathGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnglishGrade = new javax.swing.JTextField();
        txtScienceGrade = new javax.swing.JLabel();
        txtScenceGrade = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 50, 16);
        getContentPane().add(txtName);
        txtName.setBounds(140, 30, 200, 22);

        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 60, 16);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(140, 60, 200, 22);

        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 40, 16);
        getContentPane().add(txtAge);
        txtAge.setBounds(140, 90, 200, 22);

        jLabel4.setText("MathGrade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 70, 16);
        getContentPane().add(txtMathGrade);
        txtMathGrade.setBounds(140, 120, 200, 22);

        jLabel5.setText("EnglishGrade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 150, 80, 16);
        getContentPane().add(txtEnglishGrade);
        txtEnglishGrade.setBounds(140, 150, 200, 22);

        txtScienceGrade.setText("ScienceGrade");
        getContentPane().add(txtScienceGrade);
        txtScienceGrade.setBounds(40, 180, 80, 16);
        getContentPane().add(txtScenceGrade);
        txtScenceGrade.setBounds(140, 180, 200, 22);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(40, 210, 300, 23);

        jLabel7.setText("Average");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 240, 70, 16);

        txtAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAverageActionPerformed(evt);
            }
        });
        getContentPane().add(txtAverage);
        txtAverage.setBounds(140, 240, 200, 22);

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        PBO_26Maret2024.StudentRecord student = new PBO_26Maret2024.StudentRecord();
        student.setName(txtName.getText());
        student.setAddress(txtAddress.getText());
        student.setAge(Integer.parseInt(txtAge.getText()));
        student.setMathGrade(Double.parseDouble(txtMathGrade.getText()));
        student.setEnglishGrade(Double.parseDouble(txtEnglishGrade.getText()));
        student.setScienceGrade(Double.parseDouble(txtScenceGrade.getText()));
        //
        txtAverage.setText(student.getAverage()+" ");
        
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAverageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromStudentREcord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromStudentREcord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromStudentREcord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromStudentREcord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromStudentREcord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtEnglishGrade;
    private javax.swing.JTextField txtMathGrade;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScenceGrade;
    private javax.swing.JLabel txtScienceGrade;
    // End of variables declaration//GEN-END:variables
}
